adminUser:
  password: local:k8s-jenkinsx/adminUser:password
  username: fernandochew
enableDocker: false
pipelineUser:
  email: ddacagent1@gmail.com
  token: local:k8s-jenkinsx/pipelineUser:token
  username: ddacagent1
prow:
  hmacToken: local:k8s-jenkinsx/prow:hmacToken
